spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: tournament-route
          uri: http://localhost:8082
          predicates:
            - Path=/tournaments/**

        - id: matchmaking-route
          uri: http://localhost:8083
          predicates:
            - Path=/matchmaking/**

      globalcors:
        corsConfigurations:
          "[/**]": # CORS configuration for all paths
            allowedOrigins: "http://localhost:8081" # Allow frontend origin
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
