spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: tournament-route
          uri: https://tournamnet-matchmaking-tournament-service.azuremicroservices.io
          predicates:
            - Path=/tournaments/**

        - id: matchmaking-route
          uri: https://tournamnet-matchmaking-matchmaking-service.azuremicroservices.io
          predicates:
            - Path=/matchmaking/**

      globalcors:
        corsConfigurations:
          "[/**]": # CORS configuration for all paths
            allowedOrigins: "https://tournamnet-matchmaking-user-service.azuremicroservices.io" # Allow frontend origin
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
